name: Notion Automation

on:
  schedule:
    - cron: '0 5 * * *'  # Runs at 5am UTC daily
  workflow_dispatch:  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install notion-client
      - name: Run script
        run: python notion_automation.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DAILY_DB_ID: ${{ secrets.DAILY_DB_ID }}
          WEEKLY_DB_ID: ${{ secrets.WEEKLY_DB_ID }}
      
